### PR TITLE
Task assignment tests, page objects, bug fixes

### LINKED ISSUE #1076: Sentry: "TypeError: Cannot read property 'id' of null" on task list
# Problem

https://sentry.io/code-corps/code-corps-ember/issues/222295709/

### PR DESCRIPTION
**Pull request by begedin**
# What's in this PR?

This deals with the sentry issue we've been having and adds test to cover user task assignment in integration.

I'm not 100% positive this will fix the issue, but it should be the case, since I've been able to reproduce it on ocasion in development, but I'm no longer able to after this change.

The best I can figure out was, to populate the assignment dropdown, we were doing a `users.mapBy('content')`. However, in some cases, the `content` property of the `DS.PromiseObject` was `null` (not loaded yet). This happens rarely in development, more often in staging, but almost always on production.

I was implementing integration tests on the task card component and, while trying to implement the power select page object, managed to write a failing test for this without realizing. 

The fix for it was relatively simple - we do not map by content. @JoshSmith do you remember why you were mapping by content in the first place? If a user is a `DS.PromiseObject` then binding `user.username` will render nothing while the user is being loaded, but should switch to rendering `user.content.username` as soon as the loading promise resolves. This is the behaviour I'm observing locally, so there should be no need to map by content at all. Is it not the case on your side, or am I missing something.

Once the fix was applied and the failing case was passing, I wrote more tests to cover cases where we have promises and already loaded objects.

I guess, if we want nicer UX, we could have the list item component also react to `user.isLoading` and show a different state while that is happening. I believe power-select actually supports something like that in some way.

## References
Fixes #1076

### CODE REVIEW

**Comment by begedin** [comment]
@JoshSmith After rebasing, I had some items to fix. However, the tests that were failing on my machine also included some `submittable-textarea` related tests, so I added another commit to resolve those. Correct me if I'm wrong, but it looks like there was a regression introduced in 50c7c34c25a6d6d157a841ca117bc0ba52ad0e9f. With that commit, the submittable textarea no longer supported the `ctrl+enter` combination; only `cmd+enter`. I'm not sure why the tests were still passing on CI, but locally for me, the `ctrl+enter` tests were failing, so I re-added and rewrote the page objects a bit so they are more-selfcontained.

File: app/components/task-card.js [hunk 1]
```diff
@@ -70,8 +70,7 @@ export default Component.extend({
     let { currentUserId, taskUserId, users }
       = getProperties(this, 'currentUserId', 'taskUserId', 'users');
     if (users) {
-      // TODO: Replace content here!
-      return createTaskUserOptions(users.mapBy('content'), currentUserId, taskUserId);
+      return createTaskUserOptions(users, currentUserId, taskUserId);
```
Comment (begedin) [inline app/components/task-card.js]: This is the fix.

File: app/components/task-card.js [hunk 2]
```diff
@@ -100,7 +99,7 @@ export default Component.extend({
       return option;
     },
 
-    async changeUser(user) {
+    changeUser(user) {
```
Comment (begedin) [inline app/components/task-card.js]: No reason for it to be declared `async`

File: tests/integration/components/editor-with-preview-test.js [hunk 3]
```diff
@@ -182,7 +181,6 @@ test('it sends the modifiedSubmit action with ctrl+enter', function(assert) {
   });
   page.render(hbs`{{editor-with-preview modifiedSubmit="modifiedSubmit"}}`);
 
-  page.focus();
-  triggerKeyDown('Enter+cmd');
+  page.textarea.ctrlEnterSubmit();
```
Comment (begedin) [inline tests/integration/components/editor-with-preview-test.js]: If they go in pair, might as well make them a single page method.

File: tests/integration/components/submittable-textarea-test.js [hunk 4]
```diff
@@ -1,43 +1,58 @@
 import { moduleForComponent, test } from 'ember-qunit';
 import hbs from 'htmlbars-inline-precompile';
-import { triggerKeyDown, initialize } from 'ember-keyboard';
+import pageComponent from 'code-corps-ember/tests/pages/components/submittable-textarea';
+import PageObject from 'ember-cli-page-object';
```
Comment (begedin) [inline tests/integration/components/submittable-textarea-test.js]: Introduced page component.

File: tests/pages/components/editor-with-preview.js [hunk 5]
```diff
@@ -28,20 +26,12 @@ export default {
     isActive: hasClass('active')
   },
 
-  focus: triggerable('focus', 'textarea'),
+  textarea: submittableTextarea,
```
Comment (begedin) [inline tests/pages/components/editor-with-preview.js]: Extracted the textarea into a page object of its own, since it already is a component of its own

File: tests/pages/components/power-select.js [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+    options: collection({
+      itemScope: '.ember-power-select-option',
+      item: {
+        select() {
+          nativeMouseUp(this.scope);
+          return this;
+        }
+      }
+    })
+  }
```
Comment (begedin) [inline tests/pages/components/power-select.js]: The explanation is huge, but the implementation itself is tiny in comparison.

**Comment by begedin** [comment]
Test still failing on CI for some reason. Trying to figure it out.

**Comment by begedin** [comment]
@JoshSmith I've moved the commit for `submittable-textarea` into #1078 , to avoid blocking this from merge.
