### PR TITLE
Introduce serializer override for patch requests on connect account and minor fixes

### LINKED ISSUE #934: Submitting funds-recipient/details-form the first time sends a bunch of attributes which should not be sent
# Problem

The following error response is given by `stripity_stripe` the first time we try to submit the recipient details form, right after using the `create-account` form to create an account. It seems that, for some reason, our save request (a PATCH, update) is sending a bunch of attributes that should not be sent, including `tos_acceptance_date`.

Our API simply passes that through, so now Stripe thinks the date has changed and also expects an `ip` (and probably also the `user_agent`.

Due to the way the patch request behaves, I think it's a client issue we need to figure out.

```Elixir
%Stripe.APIErrorResponse{
  code: nil, 
  message: "Missing required param: ip.", 
  status_code: 400, 
  type: "invalid_request_error"
}
```

This is what our request parameters look like the first time we submit the form:

```JSON
{
  "data": {
    "id": "2",
    "attributes": {
      "bank-account-status": "pending_requirement",
      "business-name": null,
      "business-url": null,
      "can-accept-donations": true,
      "charges-enabled": true,
      "country": "US",
      "default-currency": "usd",
      "details-submitted": false,
      "display-name": null,
      "email": null,
      "inserted-at": "2017-01-03T14:51:24Z",
      "legal-entity-address-city": "Mace",
      "legal-entity-address-country": "US",
      "legal-entity-address-line1": "Delkovec 41",
      "legal-entity-address-line2": null,
      "legal-entity-address-postal-code": "49251",
      "legal-entity-address-state": "CA",
      "legal-entity-business-name": null,
      "legal-entity-business-tax-id": null,
      "legal-entity-business-tax-id-provided": false,
      "legal-entity-business-vat-id": null,
      "legal-entity-business-vat-id-provided": null,
      "legal-entity-dob-day": 1,
      "legal-entity-dob-month": 1,
      "legal-entity-dob-year": 1986,
      "legal-entity-first-name": "Nikola",
      "legal-entity-last-name": "Begedin",
      "legal-entity-gender": null,
      "legal-entity-maiden-name": null,
      "legal-entity-personal-address-city": null,
      "legal-entity-personal-address-country": "US",
      "legal-entity-personal-address-line1": null,
      "legal-entity-personal-address-line2": null,
      "legal-entity-personal-address-postal-code": null,
      "legal-entity-personal-address-state": null,
      "legal-entity-phone-number": null,
      "legal-entity-personal-id-number": null,
      "legal-entity-personal-id-number-provided": false,
      "legal-entity-ssn-last-4": "1234",
      "legal-entity-ssn-last-4-provided": false,
      "legal-entity-type": "individual",
      "legal-entity-verification-details": null,
      "legal-entity-verification-details-code": null,
      "legal-entity-verification-document": null,
      "legal-entity-verification-status": "unverified",
      "id-from-stripe": "acct_19XtdIBHJLPzE2mV",
      "managed": true,
      "personal-id-number-status": "pending_requirement",
      "recipient-status": "required",
      "support-email": null,
      "support-phone": null,
      "support-url": null,
      "tos-acceptance-date": 1483455082,
      "transfers-enabled": false,
      "updated-at": "2017-01-03T14:51:24Z",
      "verification-disabled-reason": null,
      "verification-document-status": "pending_requirement",
      "verification-due-by": null,
      "verification-fields-needed": [
        "external_account",
        "legal_entity.dob.day",
        "legal_entity.dob.month",
        "legal_entity.dob.year",
        "legal_entity.first_name",
        "legal_entity.last_name",
        "legal_entity.type"
      ]
    },
    "relationships": {
      "organization": {
        "data": {
          "type": "organization",
          "id": "1"
        }
      }
    },
    "type": "stripe-connect-account"
  }
}
```

This is what it looks like when I first refresh the page and then submit for the second time:

```JSON
{
  "data": {
    "id": "2",
    "attributes": {
      "bank-account-status": "pending_requirement",
      "business-name": null,
      "business-url": null,
      "can-accept-donations": true,
      "charges-enabled": true,
      "country": "US",
      "default-currency": "usd",
      "details-submitted": false,
      "display-name": null,
      "email": null,
      "inserted-at": "2017-01-03T14:51:24Z",
      "legal-entity-address-city": "Mace",
      "legal-entity-address-country": "US",
      "legal-entity-address-line1": "Delkovec 41",
      "legal-entity-address-line2": null,
      "legal-entity-address-postal-code": "49251",
      "legal-entity-address-state": "AL",
      "legal-entity-business-name": null,
      "legal-entity-business-tax-id": null,
      "legal-entity-business-tax-id-provided": false,
      "legal-entity-business-vat-id": null,
      "legal-entity-business-vat-id-provided": null,
      "legal-entity-dob-day": 1,
      "legal-entity-dob-month": 1,
      "legal-entity-dob-year": 1986,
      "legal-entity-first-name": "Nikola",
      "legal-entity-last-name": "Begedin",
      "legal-entity-gender": null,
      "legal-entity-maiden-name": null,
      "legal-entity-personal-address-city": null,
      "legal-entity-personal-address-country": "US",
      "legal-entity-personal-address-line1": null,
      "legal-entity-personal-address-line2": null,
      "legal-entity-personal-address-postal-code": null,
      "legal-entity-personal-address-state": null,
      "legal-entity-phone-number": null,
      "legal-entity-personal-id-number": null,
      "legal-entity-personal-id-number-provided": false,
      "legal-entity-ssn-last-4": "1234",
      "legal-entity-ssn-last-4-provided": false,
      "legal-entity-type": "individual",
      "legal-entity-verification-details": null,
      "legal-entity-verification-details-code": null,
      "legal-entity-verification-document": null,
      "legal-entity-verification-status": "unverified",
      "id-from-stripe": "acct_19XtdIBHJLPzE2mV",
      "managed": true,
      "personal-id-number-status": "pending_requirement",
      "recipient-status": "required",
      "support-email": null,
      "support-phone": null,
      "support-url": null,
      "transfers-enabled": false,
      "updated-at": "2017-01-03T14:51:24Z",
      "verification-disabled-reason": null,
      "verification-document-status": "pending_requirement",
      "verification-due-by": null,
      "verification-fields-needed": [
        "external_account",
        "legal_entity.dob.day",
        "legal_entity.dob.month",
        "legal_entity.dob.year",
        "legal_entity.first_name",
        "legal_entity.last_name",
        "legal_entity.type"
      ]
    },
    "relationships": {
      "organization": {
        "data": {
          "type": "organization",
          "id": "1"
        }
      }
    },
    "type": "stripe-connect-account"
  }
}
```

My guess is, we've set `tos_acceptance_date` locally, but the POST response returned a view that does not have this property (as we likely prefer). Now there's a mismatch between a local property and the thing that got returned from the server, so it marks `tosAcceptanceDate` as dirty. 

I think a quick and dirty fix is to roll back the model upon first save, but I'm not sure if that's enough, so we should discuss.

### PR DESCRIPTION
**Pull request by begedin**
Minor fixes in account setup process.

# What's in this PR?

Pr introduces an override for the connect account serializer, so patch requests from now on will only send dirty attributes, instead of the whole model. We may want to consider introducing this into all our `stripeX`model serializers, since behavior and issues will likely be similar.

Also introduced some minor fixes into the payments controller:
* there was a call to a renamed function that got left behind
* we didn't clear errors on subsequent requests

## References
Fixes #934

### CODE REVIEW

File: app/serializers/stripe-connect-account.js [hunk 1]
```diff
@@ -4,5 +4,15 @@ export default ApplicationSerializer.extend({
...
+
+  /**
+   * Overrides default serializeAttributes so it only serializes changed attributes,
+   * instead of the default behavior, which is all of them.
+   */
+  serializeAttribute(snapshot, json, key) {
+    if (snapshot.changedAttributes()[key] || snapshot.record.get('isNew')) {
+      this._super(...arguments);
+    }
+  },
```
Comment (JoshSmith) [inline app/serializers/stripe-connect-account.js]: Should this be our default serialization behavior everywhere? I feel like it makes more sense than constantly resending values.

Of course, there may be `required` parameters regardless of whether they have changed, so perhaps this is untenable.

File: app/controllers/project/settings/donations/payments.js [hunk 2]
```diff
@@ -176,5 +176,14 @@ export default Controller.extend({
...
+  },
+
+  _startAction() {
+    set(this, 'isBusy', true);
+    set(this, 'error', null);
+  },
+
+  _endAction() {
+    set(this, 'isBusy', false);
   }
```
Comment (JoshSmith) [inline app/controllers/project/settings/donations/payments.js]: Alpha order.

File: app/controllers/project/settings/donations/payments.js [hunk 3]
```diff
@@ -55,20 +55,20 @@ export default Controller.extend({
...
     onVerificationDocumentSubmitted(stripeFileUploadId) {
-      set(this, 'isBusy', true);
+      this._startAction();
 
       get(this, 'stripeConnectAccount')
         .then((account) => this._assignIdentityVerificationDocument(account, stripeFileUploadId))
         .catch((response) => this._handleError(response))
-        .finally(() => set(this, 'isBusy', false));
+        .finally(() => this._endAction());
     },
```
Comment (JoshSmith) [inline app/controllers/project/settings/donations/payments.js]: These actions should all probably be alpha-reordered.

File: app/serializers/stripe-connect-account.js (hunk 1 above)
Comment (begedin) [inline app/serializers/stripe-connect-account.js]: I think it should be for stripe models at minimum. Not sure about others.

File: app/controllers/project/settings/donations/payments.js (hunk 3 above)
Comment (begedin) [inline app/controllers/project/settings/donations/payments.js]: I personally prefer grouping  by behavior or order of operations, but have nothing against alpha ordering
