### PR TITLE
1083 fix unassign issue

### LINKED ISSUE #1083: Look into splitting up ember-exam partitions across CI containers
# Problem

Our Ember tests (just the `ember exam` portion) take about 3 minutes to run on Circle, and we could hypothetically speed this up to be 2-4x faster by making use of splitting containers.

If someone can look into whether this is feasible or ideal, that would be fantastic.

### LINKED ISSUE #1090: Bug: Unassignment of tasks no longer works
# Problem

I'm not sure when it happened exactly, but as far as I can tell, tasks can no longer be unassigned.

There is no difference between rendering an assigned or unassigned user in the dropdown and clicking on an assigned user calls the same method to re-assign as it would clicking some other user entirely.

### PR DESCRIPTION
**Pull request by begedin**
# What's in this PR?

This is initial work on fixing #1090

I discovered the issue while adding acceptance tests to task assignment.

Turns out, I caused the bug by removing the `mapBy('content')` within the `userOptions` method. This caused the `ember-power-select-is-equal` helper to internally fail, since it was comparing a `DS.Model` with a `DS.PromiseObject`.

This likely breaks a couple of tests, but with the computed change introduced in #1082, the sentry bug where the task list page failed to render due to fetching on id on a null object should no longer be a problem.

That being said, with the feature enabled again, it does seem like it's a bit buggy and sluggish, so maybe we should consider using another approach altogether. For example, a separate option to clear assignment might work, or we could map the options into a simpler object.

## References
Fixes #1090

### CODE REVIEW

**Comment by JoshSmith** [comment]
@begedin is this supposed to say 1083 or 1082 or something else?

File: app/services/task-assignment.js [hunk 1]
```diff
@@ -29,16 +29,25 @@ export default Service.extend({
 
   _create(user, task) {
     let store = get(this, 'store');
-    return store.createRecord('user-task', { user, task })
-                .save();
+    let userTask = store.createRecord('user-task', { user, task });
+    return userTask.save().catch(() => {
+      userTask.deleteRecord();
```
Comment (runspired) [inline app/services/task-assignment.js]: if an error occurs while creating a record, why make an API call to delete it vs just unloading it?

**Comment by JoshSmith** [comment]
@begedin I'm resolving the promise at the level of the route because I was told this evening that relying on async relationships in computeds seems like a code smell.

> Computeds based on async relationships are (in my mind) a smell. It’s really hard to control the data flow and timing of changes. At the route level or a similar higher level, it’s much easier to do this in a functional, controlled manner: either already resolved or whatever handles the promise needs to chain it and be responsible for the work.

**Comment by JoshSmith** [comment]
This appears to not have fixed tests, too.

File: app/services/task-assignment.js (hunk 1 above)
Comment (begedin) [inline app/services/task-assignment.js]: Nitpicking, `deleteRecord` is not an api call. `destroyRecord` is. 

However, you are right. `unloadRecord` is the correct choice here.

File: app/routes/project/tasks/index.js [hunk 2]
```diff
@@ -3,14 +3,22 @@ import Ember from 'ember';
...
   projectTaskBoard: service(),
 
-  model() {
-    return this.modelFor('project');
+  async model() {
+    let project = this.modelFor('project');
+    let memberships = get(project, 'organization.organizationMemberships');
+    let members = await RSVP.resolve(memberships.mapBy('member.content'));
+    return RSVP.hash({ project, members });
+  },
```
Comment (begedin) [inline app/routes/project/tasks/index.js]: In my opinion, this is worse than dealing with it in the previous manner. I'm actually not sure it works correctly.

`RSVP.resolve` is a helper that is intended to be used to simulate a promise (which resolves with the argument provided in the call immediately.

What might work here would be something like

```Javascript
let project = this.modelFor('project');
let memberPromises = get(project. 'organization.organizationMemberships').then((memberships) => {
  return memberships.map((membership) => get(membership, 'member'));
});

return RSVP.hash({ project, members: RSVP.all(memberPromises) });
```

This would return a fully resolved model. I don't think the above code would.

Possibly, this would work also, but I'm not sure:

```javascript
let project = this.modelFor('project');
let memberships = RSVP.all(get(project, 'organization.organizationMemberships').mapBy('member'));
```

But I'm pretty sure in that case, `.mapBy('member')` would just return null for each item.

Generally speaking, though, hashes in models are considered a smell to, and in the case of the previous approach, the whole purpose of `DS.PromiseObject`, `DS.PromiseArray` and `DS.PromiseManyArray`, which is what requests that `get` async relationships do, is to deal with the smell of promises in a computed.

These objects proxy all `get` and element requests to the `content` property, which is null until the associated promise resolves. The whole idea of having these classes in `ember-data` is so that promises "just work".

It's my opinion that this should be ok. Resolving all promises in the model hook, however, is probably the next best thing. The above code has a bug, though.

Just to reiterate:

```javascript
RSVP.resolve(x)
```

returns a promise which instantly resolves with x. Doesn't matter what that x is.


```javascript
RSVP.all(arrayOfPromises)
```

returns a promise which resolves when all promises in the array resolve.

**Comment by JoshSmith** [comment]
@begedin can you confirm that this is not addressing 1083 and update accordingly?

**Comment by JoshSmith** [comment]
@begedin removing ref to #1083 and replacing with what I believe is #1090.

File: app/services/task-assignment.js (hunk 1 above)
Comment (JoshSmith) [inline app/services/task-assignment.js]: I've updated now to `unloadRecord`.
